##################
#PseudoRPG Config#
##################

#DO NOT CHANGE THIS LINE! YOUR CONFIG WILL BE RESET UPON LOADING IF THIS LINE IS EDITED!
Version: 5

###########
#Inventory#
###########

Inventory:
  
  #Inventory Title Prefix (REQUIRED)
  InventoryPrefix: yellow,bold


############
#Experience#
############

Experience:
  
  #Interval of Levels for Fireworks
  #Set to 0 to disable
  FireworkInterval: 10
  
  #Numbere of fireworks spawned
  FireworkCount: 5
  
  #Display XP on BossBar?
  BossBar: true
  
  #BossBar Style (SOLID, SEGMENTED_6, SEGMENTED_10, SEGMENTED_12 or SEGMENTED_20)
  BossBarStyle: SEGMENTED_20
  
  #Delay before boss bar disappears
  BossBarDelay: 200
  
  #BossBar Message
  #%SKILL% = Skill Name
  #%LEVEL% = Level
  #%XP% = XP Amount
  #%LEVELXP% = Required XP to level up
  #%TOTALXP% = Total XP obtained
  BossBarMessage: §c§l%SKILL% - %LEVEL% (%XP% / %LEVELXP%)
  
  #XP Definitions in xp.yml File


########
#Mining#
########

Mining:
  
  #Chance of extra ore multiplier
  ExtraOreChance: 2.5
  
  #Blocks to duplicate
  Ore:
    - coal_ore
    - iron_ore
    - gold_ore
    - diamond_ore
    - emerald_ore
    - redstone_ore
    - glowing_redstone_ore
    - lapis_ore
    - quartz_ore


##########
#Smelting#
##########

Smelting:
  
  #Chance of extra ore multiplier
  ExtraOreChance: 1.0


#########
#Hunting#
#########

Hunting:

  #Modifier applied to XP gain when mob is damaged but not killed
  #Original damage = damage dealt / max mob health
  #Original damage is multiplied by modifier
  #Modifier is multiplied by XP return for killed mob
  #(damage dealt / max mob health) * (regular xp return * modifier)
  DamageModifier: 0.65
  
  #Chance of critical multiplier
  CriticalChance: 1.5
  
  #Critical damage multiplier
  CriticalMultiplier: 1.5
  
  #Chance of sweeping critical multiplier
  SweepingCriticalChance: 1.5
  
  #Critical damage multiplier
  SweepingCriticalMultiplier: 1.3